name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello World Bitch!"
          echo "Hope you like my fart!"
      - name: Print goodbye
        run: echo "Done - bye asshole!"
